global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alerts/*.yml

scrape_configs:
  - job_name: dataenginex
    metrics_path: /metrics
    static_configs:
      - targets:
          - dex-api:8000
