global:
  scrape_interval: 5s

rule_files:
  - "/etc/prometheus/rules/dataenginex-alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
scrape_configs:
  - job_name: "dataenginex"
    static_configs:
      - targets: ["dataenginex:8000"]